FROM registry.cn-shenzhen.aliyuncs.com/kye_secure/python:3.11.9

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -e /app/backend \
      -i https://mirrors.aliyun.com/pypi/simple \
      --trusted-host mirrors.aliyun.com

ENV PYTHONPATH=/app/backend
WORKDIR /app/backend

CMD ["celery", "-A", "app.workers.app", "worker", "-l", "info", "-Q", "default,parse,ocr,asr,embed"]
