"""画布节点类型名（registry、LangGraph 编译与分析共用）。"""

TEXT_INPUT_NODE_TYPE = "TextInput"
TEXT_OUTPUT_NODE_TYPE = "TextOutput"
KNOWLEDGE_SEARCH_NODE_TYPE = "KnowledgeSearch"
PROMPT_TEMPLATE_NODE_TYPE = "PromptTemplate"
LLM_CALL_NODE_TYPE = "LLMCall"
PLATFORM_TOOL_NODE_TYPE = "PlatformTool"
CONDITION_NODE_TYPE = "ConditionBranch"
RELEVANCE_GRADE_NODE_TYPE = "RelevanceGrade"
STATIC_RESPONSE_NODE_TYPE = "StaticResponse"
PARALLEL_JOIN_NODE_TYPE = "ParallelJoin"
CHAT_INPUT_NODE_TYPE = "ChatInput"
CHAT_OUTPUT_NODE_TYPE = "ChatOutput"
IMAGE_GENERATE_NODE_TYPE = "ImageGenerate"
VIDEO_GENERATE_NODE_TYPE = "VideoGenerate"

CONDITIONAL_NODE_TYPES = frozenset({CONDITION_NODE_TYPE, RELEVANCE_GRADE_NODE_TYPE})

# 兼容历史引用
PARALLEL_JOIN_TYPE = PARALLEL_JOIN_NODE_TYPE

TEXT_OUTPUT_NODE_TYPES = frozenset({TEXT_OUTPUT_NODE_TYPE, CHAT_OUTPUT_NODE_TYPE})

# 与 flow_runtime.nodes.registry.NODE_REGISTRY 键名一致（含历史别名）
CANVAS_NODE_TYPES = frozenset({
    TEXT_INPUT_NODE_TYPE,
    TEXT_OUTPUT_NODE_TYPE,
    KNOWLEDGE_SEARCH_NODE_TYPE,
    PROMPT_TEMPLATE_NODE_TYPE,
    LLM_CALL_NODE_TYPE,
    PLATFORM_TOOL_NODE_TYPE,
    CONDITION_NODE_TYPE,
    RELEVANCE_GRADE_NODE_TYPE,
    STATIC_RESPONSE_NODE_TYPE,
    PARALLEL_JOIN_NODE_TYPE,
    CHAT_INPUT_NODE_TYPE,
    CHAT_OUTPUT_NODE_TYPE,
    IMAGE_GENERATE_NODE_TYPE,
    VIDEO_GENERATE_NODE_TYPE,
})
